# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "deployment" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: pull
        uses: actions/checkout@v3

      - name: Setup Unity
        uses: kuler90/setup-unity@v1
        with:
          unity-modules: android

      - name: Activate Unity
        uses: kuler90/activate-unity@v1
        with:
          unity-username: ${{ secrets.UNITY_USERNAME }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}
          #unity-authenticator-key: ${{ secrets.UNITY_AUTHENTICATOR_KEY }}

      - name: Build Unity
        uses: kuler90/build-unity@v1
        with:
          build-target: Android
          build-path: ./build.apk
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: RageAgainstThePixel/setup-ovr-platform-util@v1

      - uses: RageAgainstThePixel/upload-meta-quest-build@v1
        with:
          appId: ${{ secrets.APP_ID }}
          appSecret: ${{ secrets.APP_SECRET }}
          apkPath: ./build.apk
